### PR TITLE
Bug fixes

### LINKED ISSUE #159: Courses are listed duplicated in student application
Courses with more than one section are listed duplicated in the preference system.

### LINKED ISSUE #163: Datagrid limits the number of applicants listed per page
The datagrid page with applicants for a section is currently limiting the number of applicants being listed. I believe this is a [limitation in the free version](https://mui.com/x/react-data-grid/pagination/#community-plan). Please either enable pagination controls (plus a search element) or work on a different alternative.

### PR DESCRIPTION
**Pull request by kukuminer**
resolves #159 
resolves #163 

student view (no duplicates this time):
image

instructor view (many students):
image
...
image

I've also noticed that loading so many rendered components seems a bit slow. Changing pages, applying filters, or searching takes a second on my local machine. Hopefully it's not too bad on prod, but maybe I can look into optimizing it eventually.

### CODE REVIEW

File: server/api/applicant.js [hunk 1]
```diff
@@ -208,20 +208,23 @@ function applicant({ app, db, pgp }) {
...
+interest, 
+qualification, 
+section.campus
+FROM course JOIN section ON course.id=section.course 
+LEFT JOIN (
+    SELECT * FROM application WHERE 
+    applicant IN (SELECT id FROM users WHERE username=$1) AND 
+    term=$2
+) AS application
+ON application.course = course.id AND application.campus=section.campus
```
Comment (jonatanschroeder) [inline server/api/applicant.js:226]: Please test to double-check this is correct.
```suggestion
LEFT JOIN application ON (
    application.applicant IN (SELECT id FROM users WHERE username=$1) AND 
    application.term=section.term AND
    application.course = course.id AND
    application.campus=section.campus)
```

**Review by jonatanschroeder — APPROVED** [review]
